on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Install Dependencies
        run: poetry install
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
      - name: Build and deploy
        run: poetry publish --build
